name: Deploy para GitHub Pages

on:
    push:
        branches:
            -main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install
      working-directory: ./ # Diretorio onde esta o package.json

    - name: Build Project
      run: npm run build # Assumindo que há um comando de build no seu projeto

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build # Diretorio onde o site é gerado
